version: '3.5'

networks:
  prodnetwork:
    driver: bridge

services:
  odoo:
    image: odoo:14.0
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - prodnetwork
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - web-data-14:/var/lib/odoo # windows
      - ./addons/:/mnt/extra-addons 
      - ./configs/odoo/odoo.conf:/etc/odoo/odoo.conf
  db:
    networks:
      - prodnetwork
    image: postgres:10
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata      
    volumes:
      - ./data/pgsql:/data/pgsql #windows for backup
      - db-data-14:/var/lib/postgresql/data #window external volume security bugs
  web:
    depends_on:
      - odoo
    networks:
      - prodnetwork
    image: 'dimaskiddo/alpine:nginx-1.12.2-novol'
    user: root
    volumes:
      - ./configs/nginx/conf.d/default.conf:/var/www/data/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
      - 443:8443
  interceptor:
        build: ./interceptor_service/
        ports:
          - "5000:5000"
        networks:
          - prodnetwork
        environment:
          - FLASK_PORT=5000
          - JWT_SECRET_KEY=t1NP63m4wnBg6nyHYKfmc2TpCOGI4nss
          - ODOO_API_KEY=933d781224995611faa0b943632c50b22c322e66
          - ODOO_API_ENDPOINT=http://odoo:8069/order
          - MONGODB_HOST=mongodb://mongo/efishery-interceptor
  mongo:
    image: mongo
    restart: always
    networks:
      - prodnetwork
    ports:
      - "27017:27017"

volumes:
    db-data-14:  #windows only
        name: db-data-14 #windows only
        external: true #windows only
    web-data-14:
        name: web-data-14
        external: true