FROM python:3.9-slim
RUN apt update && apt install -y build-essential && apt install -y libsodium23
WORKDIR /apps
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
ENTRYPOINT ["python3", "-m", "flask", "run", "--host=0.0.0.0"]